#Chapter 2


In [ ]:
#single neuron
input=[1,2,3,2.5]
weights=[0.2,0.8,-0.5,1.0]
bias=2
output=(input[0]*weights[0] + input[1]*weights[1] + input[2]*weights[2] + input[3]*weights[3] + bias)
print(output)

4.8


In [ ]:
#multi neurons, a layer
inp=[1,2,3,2.5]
w1=[0.2,0.8,-0.5,1.0]
w2=[0.5, -0.91, 0.26, -0.5]
w3=[-0.26, -0.27, 0.17, 0.87]

b1=2
b2=3
b3=0.5

o1=inp[0]*w1[0] + inp[1]*w1[1] + inp[2]*w1[2] + inp[3]*w1[3] +b1
o2=inp[0]*w2[0] + inp[1]*w2[1] + inp[2]*w2[2] + inp[3]*w2[3] +b2
o3=inp[0]*w3[0] + inp[1]*w3[1] + inp[2]*w3[2] + inp[3]*w3[3] +b3

outputs=[o1,o2,o3]
print(outputs)


[4.8, 1.21, 2.385]


In [ ]:
#laye of neurons w basic python
input1=[1,2,3,2.5]
weights1=[[0.2, 0.8, -0.5, 1.0],[0.5, -0.91, 0.26, -0.5],[-0.26,-0.27,0.17,0.87]]
biases=[2,3,0.5]
layers_out=[]

for n_weightS,n_bias in zip(weights,biases):
  n_output=0
  for n_input,n_weight in zip(input1,n_weightS):
    n_output+=n_input*n_weight
  n_output+=n_bias
  layers_out.append(n_output)

print(layers_out)


[4.8, 1.21, 2.385]


In [2]:
#Layer of neuron with numpy
import numpy as np
inp1=[1,2,3,2.5]
npweights=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
npbiases=[2,3,0.5]

np_layer_out=np.dot(npweights,inp1)+npbiases
print(np_layer_out)

[4.8   1.21  2.385]


In [3]:
#Batch of data
batchinput=[[1,2,3,2.5],[2.0,5.0,-1.0,2.0],[-1.5,2.7,3.3,-0.8]]
batchweights=[[0.2,0.8,-0.5,1],[0.5,-0.91,0.26,-0.5],[-0.26,-0.27,0.17,0.87]]
npbiases=[2,3,0.5]

batchout=np.dot(batchinput,np.array(batchweights).T)+npbiases
print(batchout)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]
